config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'chats#index'

  resources :chats do
    resources :messages
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat.rb
# frozen_string_literal: true

class Chat < ApplicationRecord
  has_many :messages, dependent: :destroy

  after_create_commit -> { broadcast_prepend_to 'chats' }
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  belongs_to :chat

  after_create_commit -> { broadcast_append_to 'messages' }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/chats_controller.rb
# frozen_string_literal: true

class ChatsController < ApplicationController
  before_action :set_chat, only: %i[show edit update destroy]

  # GET /chats or /chats.json
  def index
    @chats = Chat.all
  end

  # GET /chats/1 or /chats/1.json
  def show; end

  # GET /chats/new
  def new
    @chat = Chat.new
  end

  # GET /chats/1/edit
  def edit; end

  # POST /chats or /chats.json
  def create
    @chat = Chat.new(chat_params)

    respond_to do |format|
      if @chat.save
        format.html { redirect_to chat_url(@chat), notice: 'Chat was successfully created.' }
        format.json { render :show, status: :created, location: @chat }
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chats/1 or /chats/1.json
  def update
    respond_to do |format|
      if @chat.update(chat_params)
        format.html { redirect_to chat_url(@chat), notice: 'Chat was successfully updated.' }
        format.json { render :show, status: :ok, location: @chat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chats/1 or /chats/1.json
  def destroy
    @chat.destroy

    respond_to do |format|
      format.html { redirect_to chats_url, notice: 'Chat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_chat
    @chat = Chat.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def chat_params
    params.require(:chat).permit(:name)
  end
end

app/controllers/messages_controller.rb
# frozen_string_literal: true

class MessagesController < ApplicationController
  def create
    @message = Message.new(message_params)
    @chat = @message.chat

    respond_to do |format|
      if @message.save
        format.html do
          redirect_to chat_message_url(@message.chat, @message), notice: 'Message was successfully created.'
        end
        format.json { render :show, status: :created, location: @message }
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def message_params
    params.require(:message).permit(:body, :chat_id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/chats_helper.rb
# frozen_string_literal: true

module ChatsHelper
end

app/views/chats/_chat.html.slim
= turbo_frame_tag chat
  div
    p
      = link_to chat.name, chat, data: { turbo_frame: '_top' }

app/views/chats/_form.html.slim
= form_with(model: @chat) do |form|
  - if @chat.errors.any?
    div style="color: red"
      h2 = "#{pluralize(@chat.errors.count, "error")} prohibited this chat from being saved:"
      ul
        - @chat.errors.each do |error|
          li = error.full_message

  div
    = form.label :name, style: "display: block"
    = form.text_field :name

  div
    = form.submit

app/views/chats/create.turbo_stream.slim
= turbo_stream.update Chat.new, ""

app/views/chats/edit.html.slim
h1 Editing chat

= turbo_frame_tag @chat
  == render "form", chat: @chat

br

div
  => link_to "Show this chat", @chat
  '|
  =< link_to "Back to chats", chats_path

app/views/chats/index.html.slim
p style="color: green" = notice

= turbo_stream_from "chats"

main.container
  .header
    h1 Chats
    = link_to "New chat", new_chat_path, class: "btn btn-primary", data: { turbo_frame: dom_id(Chat.new) }

  p
    = turbo_frame_tag Chat.new

  p#chats
    = render @chats

app/views/chats/new.html.slim
h1 New chat

= turbo_frame_tag Chat.new
  == render "form", chat: @chat

br

div
  = link_to "Back to chats", chats_path

app/views/chats/show.html.slim
p style="color: green" = notice

= turbo_stream_from "messages"

main.container
  .header
    h1= @chat.name
  
  h2 Messages
  ul#messages
    - @chat.messages.each do |message|
      = render 'messages/message', message:
  
  = turbo_frame_tag @chat.messages.build
    == render 'messages/form', message: @chat.messages.build

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails7HotwireChat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.slim
= form_with(model: message, url: chat_messages_path(message.chat)) do |form|
  - if message.errors.any?
    div style="color: red"
      h2 = "#{pluralize(message.errors.count, "error")} prohibited this chat from being saved:"
      ul
        - message.errors.each do |error|
          li = error.full_message

  div
    = form.hidden_field :chat_id
    = form.label :body, style: "display: block"
    = form.text_area :body

  div
    = form.submit

app/views/messages/_message.html.slim
= turbo_frame_tag message
  li= message.body

app/views/messages/create.turbo_stream.slim
= turbo_stream.update @chat.messages.build, partial: "messages/form", locals: { message: @chat.messages.build }